-- Insert real Persian poets
INSERT INTO public.poets (name_persian, name_english, birth_year, death_year, biography_persian, biography_english) VALUES
('پروین اعتصامی', 'Parvin E''tesami', 1907, 1941, 'شاعر بزرگ زن ایرانی و از مفاخر ادبیات فارسی', 'Famous female Iranian poet'),
('شهریار', 'Shahriar', 1906, 1988, 'شاعر بزرگ معاصر تبریزی، خالق منظومه حیدربابایه سلام', 'Famous contemporary Iranian poet'),
('سهراب سپهری', 'Sohrab Sepehri', 1928, 1980, 'شاعر و نقاش برجسته معاصر ایران', 'Notable contemporary Iranian poet and painter'),
('فروغ فرخزاد', 'Forough Farrokhzad', 1934, 1967, 'شاعر نامدار معاصر ایران', 'Famous contemporary Iranian poet'),
('مهدی اخوان ثالث', 'Mehdi Akhavan-Sales', 1928, 1990, 'شاعر پرآوازه و موسیقی‌پژوه ایرانی', 'Prominent Iranian poet'),
('احمد شاملو', 'Ahmad Shamlou', 1925, 2000, 'شاعر، نویسنده، روزنامه‌نگار و مترجم معاصر ایرانی', 'Contemporary Iranian poet and writer'),
('نیما یوشیج', 'Nima Yooshij', 1895, 1959, 'پدر شعر نو فارسی', 'Father of modern Persian poetry'),
('هوشنگ ابتهاج', 'Hushang Ebtehaj', 1928, 2022, 'شاعر برجسته غزل و شعر نو معاصر', 'Prominent contemporary poet'),
('عطار نیشابوری', 'Attar of Nishapur', 1145, 1221, 'عارف و شاعر بزرگ ایرانی', 'Great Iranian mystic and poet'),
('خاقانی شروانی', 'Khaqani', 1122, 1190, 'از بزرگترین قصیده‌سرایان تاریخ شعر و ادب فارسی', 'One of the greatest Persian poets'),
('سنایی غزنوی', 'Sanai', 1080, 1131, 'شاعر و عارف بزرگ قرن ششم', 'Great poet and mystic of the 12th century'),
('بیدل دهلوی', 'Bidel Dehlavi', 1642, 1720, 'شاعر بزرگ پارسی‌گوی سبک هندی', 'Great Persian poet of the Indian style'),
('صائب تبریزی', 'Saib Tabrizi', 1592, 1676, 'بزرگترین غزل‌سرای قرن یازدهم هجری', 'Greatest ghazal writer of the 17th century'),
('رودکی', 'Rudaki', 858, 941, 'نخستین شاعر بزرگ پارسی‌گوی و پدر شعر فارسی', 'First great Persian poet, father of Persian poetry'),
('ناصرخسرو', 'Nasir Khusraw', 1004, 1088, 'شاعر، فیلسوف و جهانگرد بزرگ ایرانی', 'Great Iranian poet, philosopher and traveler'),
('وحشی بافقی', 'Vahshi Bafghi', 1532, 1583, 'شاعر بزرگ و غزل‌سرای نامدار ایرانی', 'Famous Iranian poet'),
('محتشم کاشانی', 'Mohtasham Kashani', 1500, 1588, 'مرثیه‌سرای بزرگ ادبیات فارسی', 'Great elegist of Persian literature'),
('شیخ بهایی', 'Shaykh Baha''i', 1547, 1621, 'عالم، فقیه و شاعر بزرگ عصر صفوی', 'Scholar and poet of the Safavid era'),
('فرخی سیستانی', 'Farrokhi Sistani', 950, 1037, 'از شاعران نامدار دربار محمود غزنوی', 'Famous poet of the Ghaznavid court'),
('منوچهری دامغانی', 'Manuchehri', 999, 1040, 'شاعر طبیعت‌گرای بزرگ قرن پنجم', 'Great nature poet of the 11th century'),
('انوری ابیوردی', 'Anvari', 1126, 1189, 'از برجسته‌ترین قصیده‌سرایان زبان پارسی', 'One of the most prominent Persian panegyrists'),
('نظامی گنجوی', 'Nizami Ganjavi', 1141, 1209, 'شاعر بزرگ حماسه‌سرا و داستان‌پرداز', 'Great epic and narrative poet'),
('ابوسعید ابوالخیر', 'Abu Sa''id Abu''l-Khayr', 967, 1049, 'عارف و شاعر نامدار ایرانی', 'Famous Iranian mystic and poet'),
('باباطاهر', 'Baba Taher', 938, 1010, 'عارف و شاعر دوبیتی‌سرای ایرانی', 'Iranian mystic and poet known for dubaytis'),
('فخرالدین عراقی', 'Fakhr-al-Din Iraqi', 1213, 1289, 'شاعر و عارف بزرگ قرن هفتم', 'Great poet and mystic of the 13th century'),
('امیرخسرو دهلوی', 'Amir Khusrau', 1253, 1325, 'شاعر پارسی‌گوی هندوستان', 'Persian poet of India'),
('عبید زاکانی', 'Ubayd Zakani', 1300, 1371, 'شاعر و طنزپرداز نامدار ایرانی', 'Famous Iranian poet and satirist'),
('قاآنی شیرازی', 'Qa''ani', 1808, 1854, 'از بزرگترین شاعران دوره قاجار', 'One of the greatest poets of the Qajar era'),
('ملک‌الشعرای بهار', 'Mohammad-Taqi Bahar', 1886, 1951, 'شاعر، ادیب و سیاستمدار برجسته', 'Prominent poet, scholar, and politician'),
('ایرج میرزا', 'Iraj Mirza', 1874, 1926, 'شاعر برجسته عصر مشروطه', 'Prominent poet of the Constitutional Revolution era'),
('پژمان بختیاری', 'Pejman Bakhtiari', 1900, 1974, 'شاعر و ترانه‌سرای معاصر', 'Contemporary poet and lyricist'),
('رهی معیری', 'Rahi Mo''ayyeri', 1909, 1968, 'غزل‌سرای برجسته معاصر', 'Prominent contemporary ghazal writer'),
('ابوالحسن ورزی', 'Abolhasan Varzi', 1914, 1994, 'شاعر معاصر ایرانی', 'Contemporary Iranian poet'),
('مهرداد اوستا', 'Mehrdad Avesta', 1930, 1991, 'شاعر و نویسنده معاصر', 'Contemporary poet and writer'),
('سیمین بهبهانی', 'Simin Behbahani', 1927, 2014, 'غزل‌سرای نامدار معاصر', 'Famous contemporary ghazal writer'),
('مشیری', 'Fereydoon Moshiri', 1926, 2000, 'شاعر نامدار و محبوب معاصر', 'Famous and popular contemporary poet'),
('شفیعی کدکنی', 'Mohammad-Reza Shafiei Kadkani', 1939, 2024, 'شاعر، پژوهشگر و استاد دانشگاه', 'Poet, researcher, and university professor'),
('سلمان هراتی', 'Salman Harati', 1959, 1986, 'شاعر معاصر ایرانی', 'Contemporary Iranian poet'),
('قیصر امین‌پور', 'Kaiser Aminpour', 1959, 2007, 'شاعر برجسته معاصر', 'Prominent contemporary poet'),
('حمید مصدق', 'Hamid Mosadegh', 1940, 1998, 'شاعر و حقوقدان معاصر', 'Contemporary poet and lawyer'),
('خسرو گلسرخی', 'Khosrow Golsorkhi', 1944, 1974, 'شاعر و روزنامه‌نگار انقلابی', 'Revolutionary poet and journalist'),
('سیاوش کسرایی', 'Siavash Kasraie', 1927, 1996, 'شاعر معاصر و سراینده آرش کمانگیر', 'Contemporary poet, author of Arash the Archer'),
('منوچهر آتشی', 'Manouchehr Atashi', 1931, 2005, 'شاعر نامدار و مترجم', 'Famous poet and translator'),
('فریدون توللی', 'Fereydoon Tavallali', 1919, 1985, 'شاعر و باستان‌شناس', 'Poet and archaeologist'),
('ژاله اصفهانی', 'Zhaleh Esfahani', 1922, 2007, 'شاعر زن معاصر', 'Contemporary female poet'),
('فروغی بسطامی', 'Foroughi Bastami', 1798, 1857, 'غزل‌سرای نامدار دوره قاجار', 'Famous ghazal writer of the Qajar era'),
('وصال شیرازی', 'Vesal Shirazi', 1783, 1846, 'شاعر و خطاط برجسته', 'Prominent poet and calligrapher'),
('هاتف اصفهانی', 'Hatef Esfehani', 1700, 1783, 'سراینده ترجیع‌بند معروف عرفانی', 'Author of the famous mystical Tarji-band'),
('طالب آملی', 'Taleb Amoli', 1586, 1626, 'شاعر بزرگ سبک هندی', 'Great poet of the Indian style'),
('عرفی شیرازی', 'Urfi Shirazi', 1556, 1591, 'شاعر برجسته پارسی‌گوی هند', 'Prominent Persian poet of India'),
('کلیم کاشانی', 'Kalim Kashani', 1581, 1651, 'خلاق المعانی، شاعر بزرگ سبک هندی', 'Creator of Meanings, great poet of the Indian style'),
('ابن حسام خوسفی', 'Ibn Husam Khusfi', 1381, 1470, 'شاعر حماسه‌سرای شیعی', 'Shia epic poet'),
('اوحدی مراغه‌ای', 'Awhadi Maraghai', 1274, 1338, 'عارف و شاعر صاحب جام جم', 'Mystic and poet, author of Jam-e Jam'),
('خواجوی کرمانی', 'Khwaju Kermani', 1290, 1352, 'نخل‌بند شعرا، شاعر بزرگ قرن هشتم', 'The poet''s palm-binder, great poet of the 14th century'),
('همام تبریزی', 'Homam-e Tabrizi', 1238, 1314, 'شاعر و عارف هم‌عصر سعدی', 'Poet and mystic contemporary to Saadi'),
('مجیرالدین بیلقانی', 'Mojir al-Din Beylaqani', 1100, 1190, 'شاعر قصیده‌سرای قرن ششم', 'Ode poet of the 12th century'),
('جمال‌الدین عبدالرزاق اصفهانی', 'Jamal al-Din Abd al-Razzaq Isfahani', 1130, 1192, 'شاعر برجسته اصفهانی', 'Prominent poet from Isfahan'),
('کمال‌الدین اسماعیل', 'Kamal al-Din Isma''il', 1172, 1237, 'خلاق المعانی در قصیده', 'Creator of Meanings in Odes'),
('ظهیر فاریابی', 'Zahir Faryabi', 1156, 1201, 'قصیده‌سرای بزرگ و ماهر', 'Great and skilled ode poet'),
('قطران تبریزی', 'Qatran Tabrizi', 1009, 1072, 'نخستین شاعر بزرگ پارسی‌گوی آذربایجان', 'First great Persian poet of Azerbaijan'),
('اسدی طوسی', 'Asadi Tusi', 999, 1072, 'سراینده گرشاسپ‌نامه', 'Author of Garshaspnama'),
('عنصری', 'Unsuri', 961, 1039, 'ملک‌الشعرای دربار محمود غزنوی', 'Poet Laureate of Mahmud of Ghazni''s court'),
('کسایی مروزی', 'Kisa''i Marvazi', 953, 1002, 'از پیشگامان شعر دینی در پارسی', 'Pioneer of religious poetry in Persian'),
('دقیقی', 'Daqiqi', 932, 977, 'شاعر پیشگام در حماسه‌سرایی', 'Pioneer poet in epic writing'),
('رابعه بلخی', 'Rabia Balkhi', 900, 950, 'نخستین شاعر زن پارسی‌گوی', 'First female Persian poet'),
('شهید بلخی', 'Shahid Balkhi', 850, 936, 'شاعر و فیلسوف هم‌عصر رودکی', 'Poet and philosopher contemporary to Rudaki'),
('ابوشکور بلخی', 'Abu Shakur Balkhi', 915, 960, 'سراینده آفرین‌نامه', 'Author of Afarin-nama'),
('مهستی گنجوی', 'Mahsati Ganjavi', 1089, 1159, 'شاعر زن رباعی‌سرا', 'Female quatrain poet'),
('مجدالدین همگر', 'Majd al-Din Hamgar', 1210, 1287, 'شاعر نامدار قرن هفتم', 'Famous poet of the 13th century'),
('سیف فرغانی', 'Sayf Farghani', 1200, 1300, 'شاعر منتقد روزگار مغول', 'Critical poet of the Mongol era'),
('عمادالدین نسیمی', 'Imadaddin Nasimi', 1369, 1417, 'عارف و شاعر بزرگ حروفیه', 'Great mystic and Hurufi poet'),
('هلالی جغتایی', 'Hilali Jaghatayi', 1470, 1529, 'غزل‌سرای لطیف‌طبع عصر تیموری', 'Delicate ghazal writer of the Timurid era'),
('ملاصدرا', 'Mulla Sadra', 1571, 1640, 'فیلسوف بزرگ و شاعر', 'Great philosopher and poet'),
('فیض کاشانی', 'Fayz Kashani', 1598, 1680, 'عالم، عارف و شاعر عصر صفوی', 'Scholar, mystic and poet of the Safavid era'),
('حزین لاهیجی', 'Hazin Lahiji', 1692, 1766, 'شاعر و تاریخ‌نگار برجسته', 'Prominent poet and historian'),
('طوفان مازندرانی', 'Tufan Mazandarani', 1800, 1850, 'شاعر دوره قاجار', 'Qajar era poet'),
('یغما جندقی', 'Yaghma Jandaghi', 1782, 1859, 'شاعر هجوپرداز نامدار', 'Famous satirical poet'),
('حبیب یغمایی', 'Habib Yaghmai', 1901, 1984, 'شاعر، محقق و روزنامه‌نگار', 'Poet, researcher, and journalist'),
('نادر نادرپور', 'Nader Naderpour', 1929, 2000, 'شاعر نوگرای معاصر', 'Contemporary modernist poet'),
('نصرت رحمانی', 'Nosrat Rahmani', 1929, 2000, 'شاعر عاصی معاصر', 'Rebellious contemporary poet'),
('منوچهر نیستانی', 'Manouchehr Neyestani', 1936, 1981, 'شاعر و غزل‌سرای نو', 'Poet and modern ghazal writer'),
('عمران صلاحی', 'Omran Salahi', 1946, 2006, 'شاعر و طنزپرداز برجسته', 'Prominent poet and satirist'),
('محمدعلی بهمنی', 'Mohammad-Ali Bahmani', 1942, 2024, 'غزل‌سرای نامدار معاصر', 'Famous contemporary ghazal writer'),
('حسین منزوی', 'Hossein Monzavi', 1946, 2004, 'از احیاگران غزل معاصر', 'Reviver of contemporary ghazal'),
('علی معلم دامغانی', 'Ali Moallem Damghani', 1951, NULL, 'شاعر و پژوهشگر ادبی', 'Poet and literary researcher'),
('طاهره صفارزاده', 'Tahereh Saffarzadeh', 1936, 2008, 'شاعر، محقق و مترجم قرآن', 'Poet, researcher, and Quran translator'),
('سپیده کاشانی', 'Sepideh Kashani', 1936, 1993, 'شاعر زن معاصر', 'Contemporary female poet'),
('سید حسن حسینی', 'Seyed Hassan Hosseini', 1956, 2004, 'شاعر و مترجم معاصر', 'Contemporary poet and translator'),
('محمدرضا عبدالملکیان', 'Mohammad-Reza Abdolmalekian', 1952, NULL, 'شاعر طبیعت‌گرای معاصر', 'Contemporary nature poet'),
('افشین یداللهی', 'Afshin Yadollahi', 1969, 2017, 'شاعر و ترانه‌سرای برجسته', 'Prominent poet and lyricist'),
('فاضل نظری', 'Fazel Nazari', 1979, NULL, 'غزل‌سرای پرمخاطب معاصر', 'Popular contemporary ghazal writer'),
('حامد عسکری', 'Hamed Askari', 1982, NULL, 'شاعر و نویسنده معاصر', 'Contemporary poet and writer'),
('بهاءالدین خرمشاهی', 'Baha'' al-Din Khorramshahi', 1945, NULL, 'پژوهشگر، مترجم و شاعر', 'Researcher, translator, and poet'),
('سهراب مازندرانی', 'Sohrab Mazandarani', 1888, 1950, 'شاعر آزادی‌خواه', 'Freedom-seeking poet'),
('مجدالدین میرفخرایی', 'Golchin Gilani', 1909, 1972, 'شاعر نوپرداز گیلانی', 'Modernist poet from Gilan'),
('محمود کیانوش', 'Mahmoud Kianoush', 1934, 2021, 'پایه گذار شعر کودک در ایران', 'Founder of children''s poetry in Iran'),
('بیژن جلالی', 'Bijan Jalali', 1927, 2000, 'شاعر نوپرداز معاصر', 'Contemporary modernist poet'),
('احمدرضا احمدی', 'Ahmadreza Ahmadi', 1940, 2023, 'بنیان‌گذار موج نو در شعر ایران', 'Founder of the New Wave in Iranian poetry'),
('سید علی صالحی', 'Seyed Ali Salehi', 1955, NULL, 'از پایه‌گذاران شعر گفتار', 'Founder of Speech Poetry'),
('شمس لنگرودی', 'Shams Langroudi', 1950, NULL, 'شاعر، پژوهشگر و بازیگر', 'Poet, researcher, and actor')
ON CONFLICT (name_persian) DO NOTHING;

-- Insert real quotes
INSERT INTO public.persian_quotes (text_persian, text_english, poet, poet_english, source, category, tags) VALUES
('بی‌کمالی‌های انسان از سخن پیدا شود / پسته بی‌مغز چون لب وا کند رسوا شود', 'Human imperfections are revealed through speech / A brainless pistachio is disgraced when it opens its lips', 'صائب تبریزی', 'Saib Tabrizi', 'دیوان اشعار', 'حکمت', ARRAY['حکمت']),
('آب زنید راه را هین که نگار می‌رسد / مژده دهید باغ را بوی بهار می‌رسد', 'Sprinkle water on the path, behold the beloved arrives / Give good tidings to the garden, the scent of spring arrives', 'مولانا جلال‌الدین رومی', 'Rumi', 'دیوان اشعار', 'امید', ARRAY['امید']),
('بوی جوی مولیان آید همی / یاد یار مهربان آید همی', 'The scent of the Muliyan stream is coming / The memory of the kind friend is coming', 'رودکی', 'Rudaki', 'دیوان اشعار', 'دوستی', ARRAY['دوستی']),
('ای دیو سپید پای در بند / ای گنبد گیتی ای دماوند', 'O bound white demon / O dome of the world, O Damavand', 'ملک‌الشعرای بهار', 'Mohammad-Taqi Bahar', 'دیوان اشعار', 'طبیعت', ARRAY['طبیعت']),
('به سراغ من اگر می‌آیید، نرم و آهسته بیایید، مبادا که ترک بردارد چینی نازک تنهایی من', 'If you come to me, come softly and slowly, lest the fragile porcelain of my loneliness cracks', 'سهراب سپهری', 'Sohrab Sepehri', 'دیوان اشعار', 'غم و شادی', ARRAY['غم و شادی']),
('من اینجا ریشه در خاکم / من اینجا عاشق این خاک اگر آلوده یا پاکم', 'I am rooted in the soil here / I am in love with this soil here, whether polluted or pure', 'فریدون مشیری', 'Fereydoon Moshiri', 'دیوان اشعار', 'وطن', ARRAY['وطن']),
('ای عشق همه بهانه از توست / من خامشم این ترانه از توست', 'O love, all excuses are from you / I am silent, this song is from you', 'هوشنگ ابتهاج', 'Hushang Ebtehaj', 'دیوان اشعار', 'عشق', ARRAY['عشق']),
('درد عشقی کشیده‌ام که مپرس / زهر هجری چشیده‌ام که مپرس', 'I have suffered a pain of love that you should not ask / I have tasted a poison of separation that you should not ask', 'حافظ شیرازی', 'Hafez', 'دیوان اشعار', 'عشق', ARRAY['عشق']),
('آنچه شیران را کند روبه مزاج / احتیاج است احتیاج است احتیاج', 'That which makes lions have the temperament of foxes / Is need, is need, is need', 'امیرخسرو دهلوی', 'Amir Khusrau', 'دیوان اشعار', 'حکمت', ARRAY['حکمت']),
('دریای خروشان منم، این موج ز من نیست / من قطره‌ام و این همه طوفان ز من است', 'I am a roaring sea, this wave is not from me / I am a drop and all this storm is from me', 'خاقانی شروانی', 'Khaqani', 'دیوان اشعار', 'عرفان', ARRAY['عرفان']),
('ما در پیاله عکس رخ یار دیده‌ایم / ای بی‌خبر ز لذت شرب مدام ما', 'We have seen the reflection of the beloved''s face in the cup / O ignorant one of the pleasure of our constant drinking', 'حافظ شیرازی', 'Hafez', 'دیوان اشعار', 'عرفان', ARRAY['عرفان']),
('آمدی جانم به قربانت ولی حالا چرا / بی‌وفا حالا که من افتاده‌ام از پا چرا', 'You came, my soul be sacrificed for you, but why now / Faithless, now that I have fallen, why', 'شهریار', 'Shahriar', 'دیوان اشعار', 'غم و شادی', ARRAY['غم و شادی']),
('قاصدک! هان، چه خبر آوردی؟ / از کجا وز که خبر آوردی؟', 'Dandelion! Behold, what news did you bring? / From where and from whom did you bring news?', 'مهدی اخوان ثالث', 'Mehdi Akhavan-Sales', 'دیوان اشعار', 'امید', ARRAY['امید']),
('نه تو می‌مانی و نه اندوه / و نه هیچیک از مردم این آبادی...', 'Neither you remain, nor sorrow / Nor any of the people of this village...', 'سهراب سپهری', 'Sohrab Sepehri', 'دیوان اشعار', 'زمان', ARRAY['زمان']),
('پرواز را به خاطر بسپار / پرنده مردنی است', 'Remember the flight / The bird is mortal', 'فروغ فرخزاد', 'Forough Farrokhzad', 'دیوان اشعار', 'زندگی', ARRAY['زندگی']),
('مرگ من روزی فرا خواهد رسید / در بهاری روشن از امواج نور', 'My death will arrive one day / In a spring bright with waves of light', 'فروغ فرخزاد', 'Forough Farrokhzad', 'دیوان اشعار', 'زندگی', ARRAY['زندگی']),
('روزی که برف سرخ ببارد از آسمان / بخت سیاه اهل هنر سبز می‌شود', 'The day red snow falls from the sky / The black fortune of the people of art becomes green', 'صائب تبریزی', 'Saib Tabrizi', 'دیوان اشعار', 'هنر', ARRAY['هنر']),
('بیستون را عشق کند و شهرتش فرهاد برد / رنج گل بلبل کشید و برگ گل را باد برد', 'Love dug Bisotun and Farhad took the fame / The nightingale bore the pain of the rose and the wind took its petal', 'شهریار', 'Shahriar', 'دیوان اشعار', 'عشق', ARRAY['عشق']),
('ای خدا این وصل را هجران مکن / سرخوشان عشق را نالان مکن', 'O God, do not make this union a separation / Do not make the intoxicated ones of love lament', 'مولانا جلال‌الدین رومی', 'Rumi', 'دیوان اشعار', 'عشق', ARRAY['عشق']),
('چون عهده نمی‌شود کسی فردا را / حالی خوش دار این دل پر سودا را', 'Since no one can guarantee tomorrow / Keep this passionate heart happy for now', 'عمر خیام', 'Omar Khayyam', 'دیوان اشعار', 'زندگی', ARRAY['زندگی']),
('ابر می‌بارد و من می‌شوم از یار جدا / چون کنم دل به چنین روز ز دلدار جدا', 'The cloud rains and I become separated from the beloved / How can I separate my heart from the sweetheart on such a day', 'امیرخسرو دهلوی', 'Amir Khusrau', 'دیوان اشعار', 'غم و شادی', ARRAY['غم و شادی']),
('ما ز یاران چشم یاری داشتیم / خود غلط بود آنچه می‌پنداشتیم', 'We expected friendship from friends / What we thought was wrong in itself', 'حافظ شیرازی', 'Hafez', 'دیوان اشعار', 'دوستی', ARRAY['دوستی']),
('دلا تا کی در این زندان فریب این و آن بینی / یکی زین چاه ظلمانی برون شو تا جهان بینی', 'O heart, how long will you see the deceit of this and that in this prison / Emerge once from this dark well to see the world', 'سنایی غزنوی', 'Sanai', 'دیوان اشعار', 'حکمت', ARRAY['حکمت']),
('مردی نه به قوت است و شمشیر زنی / آن است که جوری که توانی نکنی', 'Manhood is not about strength and swordplay / It is that you do not do wrong even when you can', 'سعدی شیرازی', 'Saadi', 'دیوان اشعار', 'حکمت', ARRAY['حکمت']),
('توانا بود هر که دانا بود / ز دانش دل پیر برنا بود', 'Capable is whoever is wise / Through knowledge, the old heart becomes young', 'فردوسی', 'Ferdowsi', 'دیوان اشعار', 'حکمت', ARRAY['حکمت']),
('خداوند نام و خداوند جای / خداوند روزی ده رهنمای', 'Lord of name and Lord of place / Lord who provides sustenance and guides', 'فردوسی', 'Ferdowsi', 'دیوان اشعار', 'عرفان', ARRAY['عرفان']);
